import { NextResponse } from 'next/server';
import OpenAI from 'openai';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      redditClientId,
      redditClientSecret,
      redditUsername,
      redditPassword,
      openaiApiKey,
      subreddits = 'SaaS+Entrepreneur+startups',
      postToReddit = false,
      targetSubreddit = '',
    } = body;

    // Validate required fields
    if (!redditClientId || !redditClientSecret || !openaiApiKey) {
      return NextResponse.json(
        { error: 'Reddit Client ID, Client Secret, and OpenAI API Key are required.' },
        { status: 400 }
      );
    }

    // 1. Authenticate with Reddit
    const basicAuth = Buffer.from(`${redditClientId}:${redditClientSecret}`).toString('base64');

    const grantBody =
      postToReddit && redditUsername && redditPassword
        ? `grant_type=password&username=${encodeURIComponent(redditUsername)}&password=${encodeURIComponent(redditPassword)}`
        : 'grant_type=client_credentials';

    const tokenRes = await fetch('https://www.reddit.com/api/v1/access_token', {
      method: 'POST',
      headers: {
        Authorization: `Basic ${basicAuth}`,
        'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': 'AIStartupFinder/1.0',
      },
      body: grantBody,
    });

    if (!tokenRes.ok) {
      const errText = await tokenRes.text();
      throw new Error(`Reddit auth failed: ${errText}`);
    }

    const tokenData = await tokenRes.json();
    const accessToken = tokenData.access_token;
    if (!accessToken) throw new Error('No access token from Reddit. Check your credentials.');

    // 2. Fetch hot posts
    const subredditQuery = subreddits.replace(/\s/g, '');
    const postsRes = await fetch(`https://oauth.reddit.com/r/${subredditQuery}/hot?limit=30`, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'User-Agent': 'AIStartupFinder/1.0',
      },
    });

    if (!postsRes.ok) throw new Error('Failed to fetch Reddit posts.');

    const postsData = await postsRes.json();
    const posts = postsData.data.children.map((child: any) => ({
      title: child.data.title,
      selftext: child.data.selftext,
      subreddit: `r/${child.data.subreddit}`,
      upvotes: child.data.ups,
    }));

    const meaningfulPosts = posts
      .filter((p: any) => p.selftext && p.selftext.length > 80)
      .slice(0, 12);

    if (meaningfulPosts.length === 0) {
      throw new Error('No meaningful posts found. Try different subreddits.');
    }

    // 3. Analyze with OpenAI
    const openai = new OpenAI({ apiKey: openaiApiKey });

    const prompt = `Analyze these Reddit posts from entrepreneurship communities.
Find 3 recurring problems people complain about. For each, propose a SaaS/AI startup idea.

Return ONLY valid JSON in this exact format:
{
  "ideas": [
    {
      "problem": "Detailed description of the problem",
      "solution": "The proposed startup/SaaS solution",
      "sentiment": "Frustrated",
      "source": "r/SaaS",
      "upvotes": 450,
      "title": "Catchy idea title"
    }
  ]
}

Sentiment must be one of: Frustrated, Negative, Neutral.

Posts:
${JSON.stringify(meaningfulPosts)}`;

    const completion = await openai.chat.completions.create({
      messages: [{ role: 'user', content: prompt }],
      model: 'gpt-3.5-turbo',
      response_format: { type: 'json_object' },
    });

    const resultText = completion.choices[0]?.message?.content;
    if (!resultText) throw new Error('OpenAI returned an empty response.');

    const parsedResult = JSON.parse(resultText);
    const ideasWithIds = parsedResult.ideas.map((idea: any) => ({
      ...idea,
      id: Math.random().toString(36).substring(7),
    }));

    // 4. Optionally auto-post to a subreddit
    const postedLinks: string[] = [];
    if (postToReddit && targetSubreddit && redditUsername && redditPassword) {
      for (const idea of ideasWithIds) {
        const postTitle = `[AI Idea] ${idea.title || idea.problem.slice(0, 80)}`;
        const postBody = `**Identified Problem:**\n${idea.problem}\n\n**AI Proposed Solution:**\n${idea.solution}\n\n---\n*Generated by AI Startup Idea Finder*`;

        const submitRes = await fetch('https://oauth.reddit.com/api/submit', {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${accessToken}`,
            'Content-Type': 'application/x-www-form-urlencoded',
            'User-Agent': 'AIStartupFinder/1.0',
          },
          body: new URLSearchParams({
            api_type: 'json',
            kind: 'self',
            sr: targetSubreddit.replace('r/', ''),
            title: postTitle,
            text: postBody,
          }).toString(),
        });

        if (submitRes.ok) {
          const submitData = await submitRes.json();
          const postUrl = submitData?.json?.data?.url;
          if (postUrl) postedLinks.push(postUrl);
        }
      }
    }

    return NextResponse.json({
      ideas: ideasWithIds,
      postedLinks,
      totalScraped: posts.length,
    });
  } catch (error: any) {
    console.error('startup-ideas error:', error);
    return NextResponse.json(
      { error: error.message || 'An unexpected error occurred.' },
      { status: 500 }
    );
  }
}
