import { NextResponse } from 'next/server';
import { fetchRedditPosts, getRedditAccessToken, postIdeaToReddit } from '@/lib/reddit';
import { generateIdeasLocally, generateIdeasWithOpenAI } from '@/lib/ideas';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      redditClientId = '',
      redditClientSecret = '',
      redditUsername = '',
      redditPassword = '',
      openaiApiKey = '',
      subreddits = 'SaaS+Entrepreneur+startups',
      postToReddit = false,
      targetSubreddit = '',
    } = body as {
      redditClientId?: string;
      redditClientSecret?: string;
      redditUsername?: string;
      redditPassword?: string;
      openaiApiKey?: string;
      subreddits?: string;
      postToReddit?: boolean;
      targetSubreddit?: string;
    };

    const { posts, source: dataSource } = await fetchRedditPosts(subreddits, 30, 40);

    const mode = openaiApiKey ? 'openai' : 'demo';
    const ideas = openaiApiKey
      ? await generateIdeasWithOpenAI(posts, openaiApiKey)
      : generateIdeasLocally(posts, 3);

    const postedLinks: string[] = [];
    const canPost =
      postToReddit &&
      targetSubreddit &&
      redditClientId &&
      redditClientSecret &&
      redditUsername &&
      redditPassword;

    if (canPost) {
      const accessToken = await getRedditAccessToken(
        redditClientId,
        redditClientSecret,
        redditUsername,
        redditPassword
      );

      for (const idea of ideas) {
        const postTitle = `[AI Idea] ${idea.title || idea.problem.slice(0, 80)}`;
        const postBody = `**Identified Problem:**\n${idea.problem}\n\n**AI Proposed Solution:**\n${idea.solution}\n\n---\n*Generated by AI Startup Idea Finder*`;
        const url = await postIdeaToReddit(accessToken, targetSubreddit, postTitle, postBody);
        if (url) postedLinks.push(url);
      }
    }

    return NextResponse.json({
      ideas,
      postedLinks,
      totalScraped: posts.length,
      mode,
      dataSource,
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'An unexpected error occurred.';
    console.error('startup-ideas error:', error);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
